version: '3.8' 

services:
  db:
    image: postgis/postgis:13-3.1-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: geo_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: ./web
    command: flask run --host=0.0.0.0
    volumes:
      - ./web:/code  # Pastikan volume ini benar
    ports:
      - "5000:5000"
    depends_on:
      - db

volumes:
  postgres_data: